name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set this to the node version you use

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test


      - name: Build
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Deploy to server
        run: |
          scp -r build/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Completed deployment message
        run: echo "Deployed app to server"

      
